// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: book_query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBook = `-- name: CreateBook :execresult
INSERT INTO books (title, author_id)
VALUES (?, ?)
`

type CreateBookParams struct {
	Title    string
	AuthorID int64
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBook, arg.Title, arg.AuthorID)
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author_id FROM books
WHERE id = ? 
LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(&i.ID, &i.Title, &i.AuthorID)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author_id FROM books
ORDER BY title
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(&i.ID, &i.Title, &i.AuthorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :execresult
UPDATE books
SET title = ?, author_id = ?
WHERE id = ?
`

type UpdateBookParams struct {
	Title    string
	AuthorID int64
	ID       int64
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBook, arg.Title, arg.AuthorID, arg.ID)
}
