// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Author struct {
	ID        int64
	FirstName string
	LastName  string
	Bio       sql.NullString
}

type Book struct {
	ID       int64
	Title    string
	AuthorID int64
}
